config/routes.rb
Rails.application.routes.draw do
  get "orders/process_checkout"
  get "orders/show"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :customers, controllers: {
    registrations: "customers/registrations",
    sessions: "customers/sessions"
  }

  root to: "home#index"

  resources :products

  get "cart", to: "cart#show"
  post "cart/add/:id", to: "cart#add", as: "add_to_cart"
  delete "cart/remove/:id", to: "cart#remove", as: "remove_from_cart"
  match "checkout", to: "orders#checkout", via: [ :get, :post ], as: :checkout
  post "checkout/payment", to: "orders#start_payment", as: :start_payment
  get "order/success", to: "orders#success", as: :order_success
  resources :orders, only: [ :index, :show ]
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def show
    @cart_items = Product.find(cart.keys)

    @cart_totals = @cart_items.each_with_object({}) do |product, hash|
      quantity = cart[product.id.to_s]
      hash[product.id] = product.current_price * quantity
    end

    @cart_total = @cart_totals.values.sum
  end

  def add
    product_id = params[:id].to_s
    quantity = params[:quantity].to_i
    cart[product_id] = (cart[product_id] || 0) + quantity
    redirect_to products_path, notice: "Added #{quantity} to cart."
  end

  def remove
    cart.delete(params[:id].to_s)
    redirect_to cart_path, notice: "Removed from cart."
  end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/views/cart/_form.html.erb
<%= form_with url: checkout_path, class: "shipping-form", method: :post, local: true do |form| %>
  <div class="field">
    <%= form.label :address_line1, "Address Line 1" %>
    <%= form.text_field :address_line1, class: "form-control", required: true %>
  </div>

  <div class="field">
    <%= form.label :address_line2, "Address Line 2 (Optional)" %>
    <%= form.text_field :address_line2, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city, class: "form-control", required: true %>
  </div>

  <div class="field">
    <%= form.label :province_id, "Province" %>
    <%= form.collection_select :province_id, Province.all, :id, :name, { selected: @province_id }, required: true%>
  </div>

  <div class="field">
    <%= form.label :postal_code %>
    <%= form.text_field :postal_code, class: "form-control", required: true %>
  </div>
  <div class="actions">
    <%= form.submit "Proceed to Checkout", class: "form-submit"%>
  </div>
  <!-- HIDDEN FIELDS for pricing and tax -->
  <%= form.hidden_field :subtotal %>
  <%= form.hidden_field :gst_amount %>
  <%= form.hidden_field :pst_amount %>
  <%= form.hidden_field :hst_amount %>
  <%= form.hidden_field :tax_total %>
  <%= form.hidden_field :total_price %>
  <%= form.hidden_field :order_status, value: "unpaid" %>
<% end %>


app/views/cart/add.html.erb
<h1>Cart#add</h1>
<p>Find me in app/views/cart/add.html.erb</p>

app/views/cart/remove.html.erb
<h1>Cart#remove</h1>
<p>Find me in app/views/cart/remove.html.erb</p>

app/views/cart/show.html.erb
<div class="container">
  <div class="cart-container">
    <h1 class="cart-title">Your Cart</h1>

    <% if @cart_items.any? %>
    <table class="item-table">
      <thead class="item-header">
        <tr>
          <th>Product</th>
          <th>Quantity</th>
          <th>Unit Price</th>
          <th>Total</th>
        </tr>
      </thead>
      <tbody class="item-body">
        <% @cart_items.each do |product| %>
          <tr class="item-row">
            <td class="item-name"><%= product.name %></td>
            <td class="item-quantity"><%= cart[product.id.to_s]%></td>
            <td class="item-price">$<%= '%.2f' % product.current_price.to_f %></td>
            <td class="item-total">$<%= '%.2f' % @cart_totals[product.id].to_f %></td>
            <td class="item-remove">
              <%= button_to "Remove", remove_from_cart_path(product), method: :delete, class: "remove-btn" %>
            </td>
          </tr>
        <% end %>
      </tbody>
      <tfoot class="item-footer">
        <tr>
          <td colspan="3" class="total-label">Total:</td>
          <td colspan="1" class="total-amount">$<%= '%.2f' % @cart_total %></td>
        </tr>
      </tfoot>
    </table>
    <h6 class="taxes-message">Taxes are calculated at checkout.</h6>
    <% if !customer_signed_in? %>
      <h1 class="sign-in-prompt">Sign in or create an account to complete checkout</h1>
      <ul class="sign-in-or-create-account">
        <li><%= link_to "Sign in", new_customer_session_path %></li>
        <li><%= link_to "Create Account", new_customer_registration_path %></li>
      </ul>
    <% else %>
      <h1 class="cart-title">Shipping Information</h1>
      <%= render "form", province_id:@province_id%>
    <% end %>
  <% else %>
    <p class="empty-message">Your cart is empty.</p>
  <% end %>
  </div>
</div>