config/routes.rb
Rails.application.routes.draw do
  get "orders/process_checkout"
  get "orders/show"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :customers, controllers: {
    registrations: "customers/registrations",
    sessions: "customers/sessions"
  }

  root to: "home#index"

  resources :products

  get "cart", to: "cart#show"
  post "cart/add/:id", to: "cart#add", as: "add_to_cart"
  delete "cart/remove/:id", to: "cart#remove", as: "remove_from_cart"
  match "checkout", to: "orders#checkout", via: [ :get, :post ], as: :checkout
  post "checkout/payment", to: "orders#start_payment", as: :start_payment
  get "order/success", to: "orders#success", as: :order_success
  resources :orders, only: [ :index, :show ]
end

app/views/shared/_footer.html.erb
<footer>
  <div class="footer-content">
    <p>&copy; 2025 Fonzy's Tropical Fish. All rights reserved.</p>
  </div>
</footer>

app/views/shared/_menu.html.erb
<nav class="main-menu">
  <div>
    <% if customer_signed_in? %>
    <p>Welcome back <%= current_customer.first_name %>!</p>
    <div id="logout-button-div">
      <%= button_to 'Log out', destroy_customer_session_path, method: :delete, class: 'menu-buttons' %>
      <% unless request.path == cart_path %>
        <%= link_to cart_path do %>
          <%= image_tag("icons/shopping-bag.png", alt: "Cart Icon", size: "20x20", class: "cart-icon", title: "Shopping Cart") %>
        <% end %>
      <% end %>
    </div>
    <% else %>
    <div id="login-signup-buttons-div">
      <%= button_to 'Login', new_customer_session_path, method: :get, class: 'menu-buttons'%>
      <%= button_to 'Sign Up', new_customer_registration_path, method: :get, class: 'menu-buttons' %>
      <%= link_to cart_path do %>
        <%= image_tag("icons/shopping-bag.png", alt: "Cart Icon", size: "20x20", class: "cart-icon") %>
      <% end %>
    </div>
    <% end %>
  </div>
  <h1 id="company-name-h1"><span id="fonsy">Fonsy's</span>Tropical<span id="fish">Fish</span></h1>
  <div id="menu-links-div">
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Shop", products_path %></li>
      <% if customer_signed_in?%>
        <li><%= link_to "My Orders", orders_path %></li>
      <% end %>
    </ul>
  </div>
</nav>